### ISSUE TITLE
does jetcd start to require JDK11 since version 0.6.0?

### ISSUE THREAD

**Issue by leo-lao** [etcd-io/jetcd#1047]
Your project readme.md says
> Java 8 or above is required.

but I find `jetcd` seems to require JDK11 since version 0.6.0 
I cannot run my example code using `jetcd-0.6.1` maven dependency in the JDK 8 environment.

And this also can be found in unzipped .class files from this website:
https://mvnrepository.com/artifact/io.etcd/jetcd-core/

Currently I am  concerned about this JDK dependency issue, 
In fact I don't want to upgrade my project JDK version, only because of the not-clearly-informed JDK dependency change from `jetcd`

**Comment by lburgazzoli** [comment]
From release 0.6.x the minimum java version has been bumped to 11 (https://github.com/etcd-io/jetcd/tree/jetcd-0.6.1) but due to popular demand we have temporary reverted that decision but  I have not performed any release since then.

I will probably cut a new release in the coming weeks but I can't promise anything as I'm maintaining this project in my very limited spare time.

I would also recommend to switch to java 11 as soon as possible as java 8 is quite old and I can't support it forever.

**Comment by leo-lao** [comment]
> From release 0.6.x the minimum java version has been bumped to 11 ([https://github.com/etcd-io/jetcd/tree/jetcd-0.6.1](https://github.com/etcd-io/jetcd/tree/jetcd-0.6.1?rgh-link-date=2022-03-13T13%3A51%3A15Z)) but due to popular demand we have temporary reverted that decision but I have not performed any release since then.
> 
> I will probably cut a new release in the coming weeks but I can't promise anything as I'm maintaining this project in my very limited spare time.
> 
> I would also recommend to switch to java 11 as soon as possible as java 8 is quite old and I can't support it forever.

Thank you for your effort, JDK11 is also one option for us, but we need time to estimate possible impact.
Anyway, we wil use `jetcd-0.5.x`	temporarily.
