### ISSUE TITLE
Publish etcd test rule and extension

### ISSUE THREAD

**Issue by yb172** [etcd-io/jetcd#546]
I was looking at #545 and the way to port existing `EtdClusterResource` to JUnit5 extension and found this page: https://github.com/junit-team/junit5/wiki/Third-party-Extensions.
I though it could be nice to package existing JUnit4 rule (and hopefully JUnit5 extension) as a jar so anyone who is using etcd could easily use it for their integration tests.

I've looked at maven artifacts and it doesn't look like it's published: https://mvnrepository.com/artifact/com.coreos (though examples and watch example are published...)

@fanminshi @lburgazzoli what do you think?

**Comment by fanminshi** [comment]
@yb172 that's sounds like a good idea. I think it is not too hard to publish the snapshot which is published after every pr merges as seen from this link https://oss.sonatype.org/content/repositories/snapshots/io/etcd/. You might need to play with pom.ymal to get that works. However, publish an official release including this test-extension to https://mvnrepository.com/artifact/io.etcd might need to wait until we do a 0.4.0 release since it is done manually and I think only @lburgazzoli can do it for now.
