### ISSUE TITLE
Slow grpc re-connect

### ISSUE THREAD

**Issue by Excpt0r** [etcd-io/jetcd#778]
Hi,

I'm developing an application that needs a leader/follower mechanism for high availability.
The implementation is done by using jetcd as client for an ETCD cluster, to store the current leader. Followers watch the leader key.

To detect when the ETCD instance of a watching follower is gone, gRPC keepalive is activated.
This works good, but it takes about 12 seconds between the client detecting the gone connection and the re-connect to another ETCD instance. As far as I could figure out in `ClientBuilder.java` the reconnect should be after `retryDelay=500ms`.

I'm using jetcd 0.5.4-SNAPSHOT, the logs are attached
[Reconnect.txt](https://github.com/etcd-io/jetcd/files/4892125/Reconnect.txt)

**Comment by jcferretti72** [comment]
I think what you describe is commonly known as "leader election" in distributed systems lingo.
I think the generally used implementation on etcd involves a fixed key location to identify the leader (stored in the value), associated to a lease with a TTL, and the leader having to renew periodically that lease; if/when the leader goes away etcd will remove the KV.
followers can become leaders by trying to write to the key and only succeeding when it doesn't exist
Sadly, I don't think you can use watchers for this on etcd, and you need to have followers use a polling strategy.
The reason is watchers can go silent and stop being refreshed if an etcd peer is down or becomes partitioned, depending on which peer your client watch is connected to.  Watches are in this sense eventually consistent but not fully consistent; when the etcd cluster heals itself the watcher will continue to refresh, but while the peer is down or partitioned it will not.  This prevents your leader/follower mechanism to be truly fault tolerant since the etcd cluster itself can continue to operate with a peer down or partitioned, but your leader follower mechanism will freeze working/won't update if your leader crashes and a new leader is necessary while one etcd server peer is down, if the followers trying to  become leaders happened to be connected to that peer.
With a polling strategy doing periodic GET (Range) requests with serializable=false (the default, which makes the read fully consistent / linearizable, see here: https://github.com/etcd-io/etcd/blob/master/Documentation/learning/api.md#range)

-Cristian

**Comment by Excpt0r** [comment]
@jcferretti72 thank you, I appreciate your input about the design!

I already experienced the problem that a watching client doesn't detect when the server has gone silently.
The solution I found is to activate keep-alive in the underlying grpc (it's available since jetcd 0.5.4, see here https://github.com/etcd-io/jetcd/pull/753)
To detect the connection error, this works fine, but the reconnect takes longer than I expected.

A polling strategy would maybe improve the connect behaviour, as it might be done actively after a failed polling, not automatically in the background by grpc.
If it would be possible to improve the re-connect behaviour after a failed watch, I would prefer that over polling.
The reason is that a watch can be faster than the keepalive/polling interval, in cases where the leader is gone, but not the ETCD backend of the follower.

Now that we are already talking about design:
Another solution would be to use the leader election mechanism of kubernetes itself, not ETCD (explained here for example: https://carlosbecker.com/posts/k8s-leader-election).
This would be easy to implement as a side-car container, very nice solution.
The downside is, that it is not guaranteed to get only one leader, and it relies on the kubernetes API.
When a master node dies, the API server can be unavailable for more than a minute, that's why I would like to avoid that dependency to the API.

Regards,
Alex

**Comment by jcferretti72** [comment]
Alex,

I believe I understand your comment about keep-alive in the context of jetcd client process to etcd server peer process communication; however my comment was about etcd server peer process getting partitioned from the rest of the etcd cluster: if the etcd server peer the client is connecting to, can't contact the etcd leader.  In this situation the watcher goes silent, without erroring out.

See thread here: https://github.com/etcd-io/etcd/issues/8980

The proposed solution I understand is to use the WithRequiredLeader (golang etcd client) on the watch API calls, which essentially makes them error out back to the client when the server peer that client is connecting to is out of consensus.

I do not believe that option is supported at the moment in jetcd however.  Adding the implementation shouldn't be too much work if you wanted to try sending a pull request; if you follow the golang client code you will see it essentially sets a gRPC metadata field on the stub, which should be just a few lines of code; not sure on the right API to expose in jetcd for that, however; Luca may be able to comment here on that.

Of course, once the jetcd option is available, aside from using it you would also have to codify some behavior on the code for your followers for when the watch is errored out; that likely would imply coding a retry loop from your client side.

As a side comment, I have to say I don't understand why this isn't the default behavior for a watch in etcd in general.  Watches are "eventually consistent", but a definition of eventually consistent that includes "when my server peer eventually recovers consensus" for the watch to refresh is not useful, IMHO, from the client side.  In a fault-tolerant setting with 3 or 5 etcd servers, I don't see the rationale behind having the possibility of watches going silent for long periods of time instead of notifying the client (or at least, I don't see the rationale for that being the default).

Regards,
-Cristian

**Comment by lburgazzoli** [comment]
@jcferretti72 some interceptors are added in the client manager, see https://github.com/etcd-io/jetcd/blob/master/jetcd-core/src/main/java/io/etcd/jetcd/ClientConnectionManager.java#L242-L262, not sure if that is what fit your needs but feel free to work on a PR and we can discuss it there

**Comment by Excpt0r** [comment]
@jcferretti72 thanks for pointing out that I missed the point.
Coincidentally I just had a similar issue with the lease API today - the lease keepalive is not failing on grpc level, when no leader is available. I guess that behaviour could be changed with the WithRequireLeader flag too? Would you open an issue/PR to track that topic separately?

@lburgazzoli any idea on my initially described re-connect problem?

**Comment by lburgazzoli** [comment]
@Excpt0r there is an https://github.com/etcd-io/jetcd/blob/master/jetcd-core/src/main/java/io/etcd/jetcd/Election.java api, not sure if that's what you were looking for

**Comment by Excpt0r** [comment]
Just for the record, here was a related discussion I had: 
https://github.com/grpc/grpc-java/issues/7180
