### ISSUE TITLE
OnError() contract for io.etcd.jetcd.Listener is different from io.grpc.stub.StreamObserver

### ISSUE THREAD

**Issue by jcferretti72** [etcd-io/jetcd#823]
The behavior of io.etcd.jetcd.Listener is different from io.grpc.stub.StreamObserver wrt when (and how many times) to call onError.  This is error-inviting, since the interfaces have exactly the same signatures: people familiar with gRPC APIs can assume StreamObserver behavior.

Some earlier discussion in https://github.com/etcd-io/jetcd/pull/819#issuecomment-688675196 and following comments.

**Comment by huayaoyue6** [comment]
when you use this method :
```java
default Watcher watch(ByteSequence key, WatchOption option, Consumer<WatchResponse> onNext) {
        return watch(key, option, listener(onNext));
    }
```
but have some error happens in "onNext" logic , you will get nothing tips expects "OUTBOUND RST_STREAM: streamId=5 errorCode=8" in log which in debug level , the exception is catch and mute ,  caluse the listener method:
```java
   static Listener listener(Consumer<WatchResponse> onNext) {
        return listener(onNext, t -> {
        }, () -> {
        });
    }
```
"onError" is empty. if you dont familiar with the api and you will spend some time  to find out why the watch callback only invoke once.

if you use "com.ibm.etcd:etcd-java" library, you need to implement "io.grpc.stub.StreamObserver" which you have tooverride "onError" method , also you can find message "Watch stream cancelled due to there being no active watches" in log(info level) ,  this message may helps you to find out the really reson too .

**Comment by huayaoyue6** [comment]
when you use this method :
```java
default Watcher watch(ByteSequence key, WatchOption option, Consumer<WatchResponse> onNext) {
        return watch(key, option, listener(onNext));
    }
```
but have some error happens and throw exception in "onNext" implementation, you will get nothing tips expects "OUTBOUND RST_STREAM: streamId=5 errorCode=8" in log which in debug level , the exception is catch and mute ,  caluse the listener method:
```java
   static Listener listener(Consumer<WatchResponse> onNext) {
        return listener(onNext, t -> {
        }, () -> {
        });
    }
```
"onError" is empty. if you dont familiar with the api and you will spend some time  to find out why the watch callback only invoke once.

if you use "com.ibm.etcd:etcd-java" library, you need to implement "io.grpc.stub.StreamObserver" which you have tooverride "onError" method , also you can find message "Watch stream cancelled due to there being no active watches" in log(info level) ,  this message may helps you to find out the really reson too .

**Comment by lburgazzoli** [comment]
@huayaoyue6 is there anything we can do to improve this case ?

**Comment by lburgazzoli** [comment]
@huayaoyue6 the interface 

```java
default Watcher watch(ByteSequence key, WatchOption option, Consumer<WatchResponse> onNext) {
    return watch(key, option, listener(onNext));
}
```

Is of course expected to mute exception as you don't provide any error handler so it is up to you to ensure that the implementation of `onNext` does handles its exceptions. If you need to catch errors, there are a few other methods that add support to catch exceptions like:

 https://github.com/etcd-io/jetcd/blob/38133bcad3148dcbc951f047e8532e3732986bb3/jetcd-core/src/main/java/io/etcd/jetcd/Watch.java#L41

or other variants.

Is there anything missing ?
